### PR TITLE
Update titlegen.py

### PR DESCRIPTION
**Pull request by bpeniston**
Add UC Davis chancellor

### CODE REVIEW

**Comment by fiatflux** [comment]
Linda Katehi makes much more than that. I thought about adding this with the first round of real ones, but I thought it was a bit too easy. There's something else in the pipeline, though ;-)

**Comment by bpeniston** [comment]
Ah! You’re right. I misread her salary during her 3-month suspension as her salary for the year.

http://solonews.net/353979/news/a-costly-suspension-for-uc-daviss-embattled-chancellor.html

**Comment by fiatflux** [comment]
I could have the vacation of my life for that much money ... for the better part of a decade.

**Comment by fiatflux** [comment]
I'll close this for now but thanks for the suggestion! I definitely encourage more ideas/PRs

**Pull request closed without merging**
